### ISSUE TITLE
segmentation fault (after installing PIL)

### ISSUE THREAD

**Issue by daurer** [FilipeMaia/owl#19]
When closing owl, I get a segmentation fault:11 with the error message

"Python quit unexpectedly while using the QtCore plug-in."

Can someone try to reproduce this? It might be related to a not clean deinstallation of PIL, as I played around with PIL recently in order to use the SavePNG option.

**Comment by FilipeMaia** [comment]
I cannot reproduce it.

**Comment by daurer** [comment]
It seems that my PIL installation messed up my pyqt. After removing pyqt, it works fine with pyside. We might want to move the SavePNG option away from PIL.
